# Generated by Django 6.1 on 2026-09-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='semantic_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='skill_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='match_score',
            field=models.FloatField(default=0),
        ),
    ]
