# Generated by Django 6.1 on 2026-09-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_resumeanalysis_semantic_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='recommendations',
            field=models.JSONField(default=list),
        ),
    ]
