# Generated by Django 6.1 on 2026-09-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_resumeanalysis_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='ai_feedback',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
